<a href="https://colab.research.google.com/github/dulcioris/THC/blob/main/24_10_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
print(arr[4:])

[5 6 7]


In [ ]:
print(arr[:4])

[1 2 3 4]


In [ ]:
print(arr[-3:-1])

[5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [ ]:
print(arr[::1])

[1 2 3 4 5 6 7]


In [ ]:
print(arr[::3])

[1 4 7]


In [ ]:
print(arr[::7])

[1]


In [ ]:
print(arr[::6])

[1 7]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, :])

[[ 6  7  8  9 10]]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1:, :])

[[ 6  7  8  9 10]]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1:4, 1])

[7]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1, 2])

[3]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 3])

[4 9]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, -1])

[ 5 10]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1, -3])

[3]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0, 4]) #0 es la fila y 4 la columna (la primera lista es la primera fila o renglón)

5


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 0:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,0:3])

[1 2 3]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 3])

[4 9]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 0:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 0:7])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr = np.array([1,2,3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
x = np.where(arr == 4)
print(x)

(array([0]), array([3]))


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [ ]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [ ]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [ ]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])
suma=(x+y)
print(suma)

[5 7 9]


In [ ]:
rest=(x-y)
print(rest)

[-3 -3 -3]


In [ ]:
mult=(x*y)
print(mult)

[ 4 10 18]


In [ ]:
div=(x/y)
print(div)

[0.25 0.4  0.5 ]


In [ ]:
print(f"numero pi= {np.pi}")

numero pi= 3.141592653589793


In [ ]:
ang=np.array([0,np.pi/2,np.pi])
seno=np.sin(ang)
print(f"seno: {seno}")
print(f"de loos angulos {ang}")

seno: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
de loos angulos [0.         1.57079633 3.14159265]


In [ ]:
ang=np.array([0,np.pi/2,np.pi])
np.cos=np.cos(ang)
print(f"coseno: {cos}")
print(f"de loos angulos {ang}")

TypeError: ignored

In [ ]:
x=np.array(list(range(1,9)))
print(x)

[1 2 3 4 5 6 7 8]


In [ ]:
x.reshape(-1,1).shape

(8, 1)

In [ ]:
x=np.linspace(0,1,2)
x

array([0., 1.])

In [ ]:
np.random.uniform(0,1,6) #todos tienen la misma probabilidad de salir y son 6 elementos

array([0.15276226, 0.66668328, 0.99607957, 0.28050296, 0.18479807,
       0.59404715])

In [ ]:
np.random.randint(0,10,size=3)#3 numeros aleatorios del 0 al 10

array([3, 0, 3])

In [ ]:
np.random.randint(0,10,size=1)#1 numero aleatorio del 0 al 10

array([5])

In [ ]:
n=input("Inserta un número del 1 al 10 para que la máquina lo adivine")
c=np.random.randint(0,10,size=1)
if c==n:
  print(f"tu número es: {c}")
else:
    d=np.random.randint(0,10,size=1)
    if d==n:
      print(f"tu número es: {d}")
    else:
      e=np.random.randint(0,10,size=1)
      if e==n:
        print(f"tu número es: {e}")
      else:
        f=np.random.randint(0,10,size=1)
        if f==n:
          print(f"tu número es: {f}")
        else:
          g=np.random.randint(0,10,size=1)
          if g==n:
            print(f"tu número es: {g}")
          else:
            h=np.random.randint(0,10,size=1)
            if h==n:
              print(f"tu número es: {h}")
            else:
              i=np.random.randint(0,10,size=1)
              if i==n:
                print(f"tu número es: {i}")
              else:
              j=np.random.randint(0,10,size=1)
                if j==n:
                  print(f"tu número es: {j}")
                else:
                k=np.random.randint(0,10,size=1)
                  if k==n:
                  print(f"tu número es: {k}")
                  else:
                    l=np.random.randint(0,10,size=1)
                    print(f"tu número es: {l}")


IndentationError: ignored

In [ ]:
n=input("Inserta un número del 1 al 10 para que la máquina lo adivine")
c=np.random.randint(0,10,size=1)
for n:
  print(c)
  if c == n:
    break

SyntaxError: ignored

In [ ]:
n=input("Inserta un número del 1 al 10 para que la máquina lo adivine")
i = np.random.randint(0,10,size=1)
while i < 11 :

  if i == n:
    break
  print(i)

Inserta un número del 1 al 10 para que la máquina lo adivine5


<ipython-input-88-cb03076033e2>:5: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if i == n:


Se han truncado las últimas 5000 líneas del flujo de salida.
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]
[7]